# Generated by Django 4.1.1 on 2022-09-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="employee",
            fields=[
                ("no", models.AutoField(primary_key=True, serialize=False)),
                ("fname", models.CharField(max_length=20)),
                ("lname", models.CharField(max_length=20)),
                ("gender", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("hobbies", models.CharField(max_length=200)),
                ("department", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="student",
            fields=[
                ("student_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=200, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_no", models.IntegerField()),
                ("password", models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name="uniq",
            fields=[
                ("uniq_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=200, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("address", models.CharField(max_length=200)),
                ("phone_no", models.IntegerField()),
                ("gender", models.CharField(max_length=200)),
                ("department", models.CharField(max_length=200)),
            ],
        ),
    ]
